name: .NET CI for ATMApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ATMApp.sln
      working-directory: finalcs509

    - name: Run StyleCop Analyzers
      run: dotnet build ATMApp.sln -warnaserror
      working-directory: finalcs509

    - name: Build Debug
      run: dotnet build ATMApp.sln --configuration Debug --no-restore
      working-directory: finalcs509

    - name: Build Release
      run: dotnet build ATMApp.sln --configuration Release --no-restore
      working-directory: finalcs509

    - name: Run Tests
      run: dotnet test ATMApp.Tests/ATMApp.Tests.csproj --no-build --verbosity normal
      working-directory: finalcs509

    - name: (Optional) Generate Documentation
      run: echo "📝 Add docgen command here (e.g. DocFX, Sandcastle, etc.)"
      working-directory: finalcs509

