name: CI/CD Pipeline for ATMApp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9 Preview
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        include-prerelease: true

    - name: Install dependencies
      run: dotnet restore finalcs509/ATMApp.sln

    - name: Run StyleCopAnalyzers
      run: dotnet build finalcs509/ATMApp.sln -c Release /warnaserror

    - name: Build (Debug)
      run: dotnet build finalcs509/ATMApp.sln -c Debug

    - name: Run Tests with Coverage
      run: dotnet test finalcs509/ATMApp.sln --collect:"XPlat Code Coverage"

    - name: Generate Code Coverage Report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.26
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coverage-report'
        reporttypes: 'HtmlInline_AzurePipelines'

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage-report

    - name: Build Documentation (optional)
      run: echo "Generate docs here (e.g. with Sandcastle, DocFX, etc.)"
